piro20_Ajax_Pirostagram/config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('posts.urls')),
]

piro20_Ajax_Pirostagram/posts/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *

app_name = 'posts'
urlpatterns = [
    path('',posts_list,name='list'),
    path("create/",create,name='create'),
    path("detail/<int:pk>/",detail,name='detail'),
    path("delete/<int:pk>/",delete,name='delete'),
    path('like_ajax/', like_ajax, name='like_ajax'),
    path('comment/create/',comment_create,name='comment_create'),
    path('comment/delete/<int:pk>/',comment_delete,name='comment_delete'),
]

piro20_Ajax_Pirostagram/posts/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
    title=models.CharField(max_length=255)
    content=models.TextField()
    like=models.BooleanField(default=False)
    date=models.DateTimeField(default=timezone.now)

class Comment(models.Model):
    post=models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    content=models.TextField()
    

# Create your models here.

piro20_Ajax_Pirostagram/posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=["title", "content"]

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['content']

piro20_Ajax_Pirostagram/posts/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse

# Create your views here.
def posts_list(request):
    posts=Post.objects.all()
    ctx={'posts':posts}
    return render(request,'posts_list.html',ctx)

def create(request):
    if request.method=='GET':
        form=PostForm()
        ctx={'form':form}
        return render(request, 'posts_create.html', ctx)
    
    form=PostForm(request.POST, request.FILES)
    if form.is_valid():
        post_instance=form.save()
    return redirect('posts:list')

def detail(request, pk):
    post = get_object_or_404(Post, id=pk)
    comments = Comment.objects.filter(post=post)
    ctx = {'comments': comments, 'post': post}
    return render(request, 'posts_detail.html', ctx)

def delete(request, pk):
  if request.method == 'POST':
    Post.objects.get(id=pk).delete()
  return redirect('posts:list')

import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def like_ajax(request):
    req=json.loads(request.body)
    post_id=req['id']

    post=Post.objects.get(id=post_id)

    post.like = not post.like  

    post.save()

    return JsonResponse({'id':post_id,'like': post.like})


@csrf_exempt
def comment_create(request):
    if request.method == 'POST':
        try:
            req = json.loads(request.body)
            post_id = req.get('id')
            post = get_object_or_404(Post, id=post_id)

            comment = Comment.objects.create(
                post=post,
                content=req.get("comment", ""),
            )
            comment_id = comment.id
            post.comments.add(comment)
            return JsonResponse({'id': post_id, 'comment': req.get("comment", ""), 'comment_id': comment_id})
        except Post.DoesNotExist:
            return JsonResponse({'error': 'Post not found'}, status=404)
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=500)
    else:
        # GET 요청 응답 처리
        return JsonResponse({'error': 'GET request is not supported'}, status=405)


@csrf_exempt
def comment_delete(request, pk):
  try:
        req = json.loads(request.body)
        comment_id = req['comment_id']

        comment = Comment.objects.get(id=comment_id)
        comment.delete()

        return JsonResponse({'post_id': pk, 'comment_id': comment_id})
  except Comment.DoesNotExist:
        return JsonResponse({'error': 'Comment not found'}, status=404)
  except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)

piro20_Ajax_Pirostagram/templates/posts_create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <form action="" method="post" enctype="multipart/form-data">
        {%csrf_token%} {{form.as_p}}
        <button class="btn btn-success">등록하기</button>
    </form>
  </body>
</html>

piro20_Ajax_Pirostagram/templates/posts_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/posts_detail.css' %}" />
    <title>Pirostagram</title>
  </head>
  <body>
    <div class="post post-id-{{ post.id }}">
      <div class="post-container">
        <img src="http://placekitten.com/200/300" />
        <p>{{post.title}}</p>
        {% if post.like %}
        <div class="post__like-btn" onclick="onClickLike('{{ post.id }}')">
          ❤️
        </div>
        {% else %}
        <div class="post__like-btn" onclick="onClickLike('{{ post.id }}')">
          🤍
        </div>
        {% endif %}
        <p>{{post.content}}</p>
        <form action="{% url 'posts:delete' post.pk %}" method="POST">
          {%csrf_token%}
          <button type="submit">삭제하기</button>
        </form>
        <a href="{% url 'posts:list'%}"><button>목록보기</button></a>
      </div>
      <div class="comment-container">
        {% for comment in comments %}
        <div class="comment comment-{{comment.id}}">
          {{comment.content}}
          <div onclick="onClickDelete('{{ post.id }}', '{{ comment.id }}')">
            삭제
          </div>
        </div>
        {% endfor %}
      </div>
      <div class="input-container">
        <input
          type="text"
          id="comment-input"
          placeholder="댓글을 작성하세요."
        />
        <button
          onclick="onClickCreate('{{ post.id }}',document.getElementById('comment-input').value)"
        >
          작성
        </button>
      </div>
    </div>
    <script>
      const requestLike = new XMLHttpRequest();

      const onClickLike = (id) => {
        const url = "/like_ajax/";
        requestLike.open("POST", url, true);
        requestLike.setRequestHeader(
          "Content-Type",
          "application/x-www-form-urlencoded"
        );
        requestLike.send(JSON.stringify({ id: id }));
      };

      requestLike.onreadystatechange = () => {
        if (requestLike.readyState === XMLHttpRequest.DONE) {
          if (requestLike.status < 400) {
            const { id, like } = JSON.parse(requestLike.responseText);
            const element = document.querySelector(
              `.post-id-${id} .post__like-btn`
            );
            const newLikeStatus = !like;

            element.innerHTML = newLikeStatus ? "🤍" : "❤️";
          }
        }
      };

      const onClickCreate = (id, comment) => {
        const requestClick = new XMLHttpRequest();
        const url = "/comment/create/";
        requestClick.open("POST", url, true);
        requestClick.setRequestHeader(
          "Content-Type",
          "application/x-www-form-urlencoded"
        );
        requestClick.send(JSON.stringify({ id: id, comment: comment }));

        requestClick.onreadystatechange = () => {
          if (requestClick.readyState === XMLHttpRequest.DONE) {
            if (requestClick.status < 400) {
              const { id, comment, comment_id } = JSON.parse(
                requestClick.responseText
              );
              const element = document.querySelector(`.comment-container`);
              element.innerHTML =
                element.innerHTML +
                `<div class='comment comment-${comment_id}'>${comment}<div
                  onclick="onClickDelete('${id}', '${comment_id}')"
                >
                  삭제
                </div></div>`;
            }
          }
        };
      };

      const onClickDelete = (post_id, comment_id) => {
        const requestClick = new XMLHttpRequest();
        const url = `/comment/delete/${post_id}/`;
        requestClick.open("POST", url, true);
        requestClick.setRequestHeader(
          "Content-Type",
          "application/x-www-form-urlencoded"
        );
        requestClick.send(
          JSON.stringify({ post_id: post_id, comment_id: comment_id })
        );

        requestClick.onreadystatechange = () => {
          if (requestClick.readyState === XMLHttpRequest.DONE) {
            if (requestClick.status < 400) {
              const { post_id, comment_id } = JSON.parse(requestClick.response);
              const element = document.querySelector(`.comment-${comment_id}`);
              element.innerHTML = ``;
            }
          }
        };
      };
    </script>
  </body>
</html>

piro20_Ajax_Pirostagram/templates/posts_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/posts_list.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/remixicon@4.1.0/fonts/remixicon.css"
      rel="stylesheet"
    />
    <title>Document</title>
  </head>
  <body>
    <header>
      <div></div>
      <div>Pirostagram</div>
      <a href="{%url 'posts:create'%}"><i class="ri-add-box-line"></i></a>
    </header>
    <main>
      {% for post in posts %}

      <div class="post post-id-{{ post.id }}">
        <a href="{%url 'posts:detail' post.pk%}"
          ><img src="http://placekitten.com/200/300"
        /></a>
        <div class="title-area">
          <a href="{%url 'posts:detail' post.pk%}"><div>{{post.title}}</div></a>

          {% if post.like %}
          <div class="post__like-btn" onclick="onClickLike('{{ post.id }}')">
            ❤️
          </div>
          {% else %}
          <div class="post__like-btn" onclick="onClickLike('{{ post.id }}')">
            🤍
          </div>
          {% endif %}
        </div>
        <div class="content">{{post.content}}</div>
      </div>

      {% endfor %}
    </main>
    <script>
      const requestLike = new XMLHttpRequest();

      const onClickLike = (id) => {
        const url = "/like_ajax/";
        requestLike.open("POST", url, true);
        requestLike.setRequestHeader(
          "Content-Type",
          "application/x-www-form-urlencoded"
        );
        requestLike.send(JSON.stringify({ id: id }));
      };

      requestLike.onreadystatechange = () => {
        if (requestLike.readyState === XMLHttpRequest.DONE) {
          if (requestLike.status < 400) {
            const { id, like } = JSON.parse(requestLike.responseText);
            const element = document.querySelector(
              `.post-id-${id} .post__like-btn`
            );
            const newLikeStatus = !like;

            element.innerHTML = newLikeStatus ? "🤍" : "❤️";
          }
        }
      };
    </script>
  </body>
</html>