SWIDEA_SITE/config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ideas.urls')),
    path('devtool/',include('devtools.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/devtools/urls.py
from django.urls import path
from .views import *

app_name = 'devtools'

urlpatterns = [
    path('',tool_list,name='list'),
    path('create/',create, name='create'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('update/<int:pk>/', update, name='update'),
]

SWIDEA_SITE/ideas/urls.py
from django.urls import path
from .views import *

app_name = 'ideas'

urlpatterns = [
    path('',idea_list,name='list'),
    path('create/',create, name='create'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('update/<int:pk>/', update, name='update'),
]

SWIDEA_SITE/devtools/models.py
from django.db import models

# Create your models here.

class Devtool(models.Model):
    name=models.CharField('이름',max_length=24)
    kind=models.CharField('종류',max_length=24)
    content=models.CharField('내용',max_length=200)

    def __str__(self):
        return self.name

SWIDEA_SITE/ideas/models.py
from django.db import models
from devtools.models import Devtool

# Create your models here.

class Idea(models.Model):
    title=models.CharField('제목',max_length=24)
    devtool=models.ForeignKey(Devtool,on_delete=models.CASCADE, verbose_name='개발툴')
    image=models.ImageField('이미지',blank=True, upload_to='ideas/%Y%m%d')
    content=models.CharField('내용',max_length=500)
    interest=models.IntegerField('관심도',default=0)
    mark=models.BooleanField(default=False)

    def __str__(self):
        return self.title

SWIDEA_SITE/devtools/forms.py
from django import forms
from .models import Devtool

class DevtoolForm(forms.ModelForm):
    class Meta():
        model = Devtool
        fields = '__all__'

SWIDEA_SITE/ideas/forms.py
from django import forms
from .models import Idea

class IdeaForm(forms.ModelForm):
    class Meta():
        model = Idea
        exclude = ['mark']

SWIDEA_SITE/devtools/views.py
from django.shortcuts import render,redirect
from .forms import DevtoolForm
from .models import Devtool
from ideas.models import Idea

# Create your views here.

def tool_list(request):
    devtools=Devtool.objects.all()
    ctx={'devtools':devtools}
    return render(request,'devtools/devtool_list.html',ctx)

def create(request):
    if request.method=='GET':
        form=DevtoolForm()
        ctx={'form':form}
        return render(request, 'devtools/devtool_create.html', ctx)
    
    form=DevtoolForm(request.POST, request.FILES)
    if form.is_valid():
        Devtool_instance=form.save()
    return redirect('devtools:detail',Devtool_instance.id)

def detail(request,pk):
    devtool=Devtool.objects.get(id=pk)
    ideas=Idea.objects.all()
    ideas_filter=Idea.objects.filter(devtool__name=devtool.name)
    ctx={'devtool':devtool,'ideas':ideas_filter}
    return render(request,'devtools/devtool_detail.html',ctx)

def delete(request,pk):
    if request.method == 'POST':
        Devtool.objects.get(id=pk).delete()
    return redirect('devtools:list')

def update(request,pk):
     devtool=Devtool.objects.get(id=pk)

     if request.method=='GET':
        form=DevtoolForm(instance=devtool)
        ctx={'form':form, 'pk':pk}
        return render(request, 'devtools/devtool_update.html',ctx)
     else:    
        form=DevtoolForm(request.POST, request.FILES, instance=devtool)
        if form.is_valid():
            form.save()
        return redirect('devtools:detail',pk)

SWIDEA_SITE/ideas/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
from .forms import IdeaForm
from .models import Idea

# Create your views here.

def idea_list(request):
     sort_option = request.GET.get('sort_option', '')

     if sort_option:
        if sort_option == 'name':
            ideas = Idea.objects.order_by('title')
        elif sort_option == 'interest':
            ideas = Idea.objects.order_by('interest')
        else:
            ideas = Idea.objects.all()
     else:
        ideas = Idea.objects.all()
     ctx={'ideas':ideas}
     return render(request,'ideas/idea_list.html',ctx)

def create(request):
    if request.method=='GET':
        form=IdeaForm()
        ctx={'form':form}
        return render(request, 'ideas/idea_create.html', ctx)
    
    form=IdeaForm(request.POST, request.FILES)
    if form.is_valid():
        idea_instance=form.save()
    return redirect('ideas:detail',idea_instance.id)

def detail(request,pk):
    idea=Idea.objects.get(id=pk)
    ctx={'idea':idea}
    return render(request,'ideas/idea_detail.html',ctx)

def delete(request, pk):
  if request.method == 'POST':
    Idea.objects.get(id=pk).delete()
  return redirect('/')

def update(request, pk):
   idea=Idea.objects.get(id=pk)

   if request.method=='GET':
      form=IdeaForm(instance=idea)
      ctx={'form':form, 'pk':pk}
      return render(request, 'ideas/idea_update.html',ctx)
   
   else:    
    form=IdeaForm(request.POST, request.FILES, instance=idea)
    if form.is_valid():
            form.save()
    return redirect('ideas:detail',pk)

SWIDEA_SITE/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'ideas/style.css' %}"
    />
    {%block head%} {% endblock %}
  </head>
  <body>
    <header>
      <div id="idea-create">
        <a href="{% url 'ideas:create' %}">
          <p>아이디어 등록</p>
        </a>
      </div>
      <div id="idea-list">
        <a href="/">
          <p>아이디어 관리</p>
        </a>
      </div>

      <div id="tool-create">
        <a href="{% url 'devtools:create' %}">
          <p>개발툴 등록</p>
        </a>
      </div>
      <div id="tool-list">
        <a href="{% url 'devtools:list' %}">
          <p>개발툴 관리</p>
        </a>
      </div>
    </header>
    <main>{%block content%} {%endblock%}</main>
  </body>
</html>

SWIDEA_SITE/templates/devtools/devtool_create.html
{% extends 'base.html' %} {% load static %} {%block head%}
<title>툴 추가</title>
{%endblock%} {%block content%}
<div id="create">
  <form action="" method="post" enctype="multipart/form-data">
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-success">등록하기</button>
  </form>
</div>
{%endblock%}

SWIDEA_SITE/templates/devtools/devtool_detail.html
{% extends 'base.html' %} {% load static %} {%block head%}
<title>툴 추가</title>
{%endblock%} {%block content%}

<h2>{{devtool.name}}</h2>
<p>종류: {{devtool.kind}}</p>
<p>개발툴 설명: {{devtool.content}}</p>
{% if ideas %}
<p>만들 수 있는 아이디어 목록</p>
  {% for idea in ideas %}
    <a href={% url 'ideas:detail' pk=idea.id%}>- {{idea.title}}</a>
    <br>
  {% endfor %}
{%endif%}

<form action="{% url 'devtools:delete' devtool.pk %}" method="POST">
  {%csrf_token%}
  <a href="{% url 'devtools:update' devtool.pk %}" class="btn">수정하기</a>
  <button type="submit" id="submit-btn" class="btn">삭제하기</button>
  <a href="{% url 'devtools:list' %}" class="btn">목록</a>
</form>
{%endblock%}

SWIDEA_SITE/templates/devtools/devtool_list.html
{% extends 'base.html' %} {% load static %} {%block head%}
<title>툴 추가</title>
{%endblock%} {%block content%}
<div id="info">
  <p>develop tool list</p>
</div>
<div id="tool-list">
  <br />
  {% for devtool in devtools %}
  <div class="devtool">
    <a href="{% url 'devtools:detail' devtool.pk %}">
      <div>{{devtool.name}}</div>
    </a>
    <div>{{devtool.kind}}</div>
    <div>{{devtool.content}}</div>
  </div>
  {% endfor %}
</div>
{%endblock%}

SWIDEA_SITE/templates/devtools/devtool_update.html
{% extends 'base.html' %} {% load static %} {%block head%}
<title>툴 추가</title>
{%endblock%} {%block content%}
<form
  action="{% url 'devtools:update' pk %}"
  method="post"
  enctype="multipart/form-data"
>
  {%csrf_token%} {{form.as_p}}
  <button class="btn btn-primary">수정 완료</button>
</form>
{%endblock%}

SWIDEA_SITE/templates/ideas/idea_create.html
{% extends 'base.html' %} {% load static %} {%block head%}
<title>아이디어 추가</title>
{%endblock%} {%block content%}
<div id="create">
  <form action="" method="post" enctype="multipart/form-data">
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-success">등록하기</button>
  </form>
</div>
{%endblock%}

SWIDEA_SITE/templates/ideas/idea_detail.html
{% extends 'base.html' %} {% load static %} {%block head%}
<title>아이디어</title>
<link
  href="https://cdn.jsdelivr.net/npm/remixicon@4.1.0/fonts/remixicon.css"
  rel="stylesheet"
/>
{%endblock%} {%block content%}
<div>
  {% if idea.image.url != null and idea.image.url != '' %}
  <img src="{{ idea.image.url }}" alt="대체텍스트" />
  {% else %}
  <img src="../../static/ideas/no_img.png" alt="대체텍스트" />
  {% endif %}
  <div id="detail"></div>
  <div id="title-container">
    <p>{{idea.title}}</p>
    {% if idea.mark %}
    <i class="ri-star-fill"></i>
    {% else %}
    <i class="ri-star-line"></i>
    {% endif %}
  </div>
  <p>아이디어 관심도: {{idea.interest}}</p>
  <a href="{% url 'devtools:detail' pk=idea.devtool.id %}">
    <p>개발툴: {{idea.devtool}}</p>
  </a>
  <p>아이디어 설명: {{idea.content}}</p>
</div>
<form action="{% url 'ideas:delete' idea.pk %}" method="POST">
  {%csrf_token%}
  <a href="{% url 'ideas:update' idea.pk %}" class="btn">수정하기</a>
  <button type="submit" id="submit-btn" class="btn">삭제하기</button>
  <a href="{% url 'ideas:list' %}" class="btn">목록</a>
</form>
{%endblock%}

SWIDEA_SITE/templates/ideas/idea_list.html
{% extends 'base.html' %} {% load static %} {%block head%}
<link
  href="https://cdn.jsdelivr.net/npm/remixicon@4.1.0/fonts/remixicon.css"
  rel="stylesheet"
/>
<script defer src="../../static/ideas/script.js"></script>

<title>아이디어 리스트</title>
{%endblock%} {%block content%}

<div id="info">
  <p>Idea List</p>
  <select name="sort" id="sort">
    <option value="" id="">------</option>
    <option value="recently" id="recently">최신순(기본)</option>
    <option value="interest" id="interest">관심도순</option>
    <option value="name" id="name">이름순</option>
  </select>
</div>
<div id="list">
  {% for idea in ideas %}
  <div class="idea">
    <div class="image">
      {% if idea.image.url != null and idea.image.url != '' %}
      <img src="{{ idea.image.url }}" alt="대체텍스트" />
      {% else %}
      <img src="../../static/ideas/no_img.png" alt="대체텍스트" />
      {% endif %} {% if idea.mark %}
      <i
        class="ri-star-fill"
        style="color: yellow"
        onclick="changeMark(this)"
      ></i>
      {% else %}
      <i
        class="ri-star-line"
        style="color: yellow"
        onclick="changeMark(this)"
      ></i>
      {% endif %}
    </div>
    <a href="{% url 'ideas:detail' idea.pk %}">
      <div class="title">{{idea.title}}</div>
    </a>
    <div class="tool">{{idea.devtool}}</div>
    <div class="interest-container">
      <p onclick="changeInterest(this,'{{idea.id}}',-1)"><</p>
      <div class="interest">{{idea.interest}}</div>
      <p onclick="changeInterest(this,'{{idea.id}}',1)">></p>
    </div>
  </div>
  {% endfor %}
</div>
{%endblock%}

SWIDEA_SITE/templates/ideas/idea_update.html
{% extends 'base.html' %} {% load static %} {%block head%}
<title>아이디어 수정하기</title>
{%endblock%} {%block content%}
<form
  action="{% url 'ideas:update' pk %}"
  method="post"
  enctype="multipart/form-data"
>
  {%csrf_token%} {{form.as_p}}
  <button class="btn btn-primary">수정 완료</button>
</form>
{%endblock%}